# Generated by Django 4.2.7 on 2025-10-29 01:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('disponible', '✅ Disponible'), ('mantenimiento', '🔧 En Mantenimiento'), ('en_uso', '🛠️ En Uso'), ('perdida', '❌ Perdida')], default='disponible', max_length=20)),
                ('cantidad_total', models.IntegerField(default=1)),
                ('cantidad_disponible', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', '📋 Planificada'), ('en_proceso', '🚧 En Proceso'), ('suspendida', '⏸️ Suspendida'), ('finalizada', '✅ Finalizada'), ('cancelada', '❌ Cancelada')], default='planificada', max_length=20)),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'permissions': [('puede_ver_dashboard', 'Puede ver dashboard'), ('puede_gestionar_productos', 'Puede gestionar productos'), ('puede_ver_reportes', 'Puede ver reportes'), ('puede_gestionar_usuarios', 'Puede gestionar usuarios'), ('puede_gestionar_obras', 'Puede gestionar obras'), ('puede_gestionar_presupuestos', 'Puede gestionar presupuestos')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('admin', '👑 Administrador'), ('vendedor', '💰 Vendedor'), ('cliente', '👤 Cliente'), ('constructor', '👷 Constructor')], default='cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion_servicios', models.TextField()),
                ('materiales_incluidos', models.BooleanField(default=True)),
                ('mano_obra_incluida', models.BooleanField(default=True)),
                ('impuestos_incluidos', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('solicitado', '📨 Solicitado'), ('en_revision', '🔍 En Revisión'), ('aceptado', '✅ Aceptado'), ('rechazado', '❌ Rechazado'), ('replanteado', '🔄 Replanteado')], default='solicitado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('notas_cliente', models.TextField(blank=True, null=True)),
                ('notas_constructor', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_cliente', to=settings.AUTH_USER_MODEL)),
                ('constructor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'constructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_constructor', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='gestion.obra')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='obras_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='constructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'constructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_constructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('disponible', '✅ Disponible'), ('mantenimiento', '🔧 En Mantenimiento'), ('alquilada', '🚚 Alquilada'), ('reparacion', '⚠️ En Reparación')], default='disponible', max_length=20)),
                ('costo_alquiler_dia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('mano_obra', 'Mano de Obra'), ('maquinaria', 'Maquinaria'), ('herramienta', 'Herramienta'), ('servicio', 'Servicio'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('herramienta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.herramienta')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.maquinaria')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.material')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.presupuesto')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
            },
        ),
        migrations.AddField(
            model_name='herramienta',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
