# Generated by Django 4.2.7 on 2025-11-01 18:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_herramienta_obra_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempresupuesto',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Item de Presupuesto', 'verbose_name_plural': 'Items de Presupuesto'},
        ),
        migrations.RenameField(
            model_name='presupuesto',
            old_name='fecha_vencimiento',
            new_name='fecha_validez',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='impuestos_incluidos',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='mano_obra_incluida',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='materiales_incluidos',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='notas_cliente',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='notas_constructor',
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itempresupuesto',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='codigo_presupuesto',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='dias_validez',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='tipo',
            field=models.CharField(choices=[('material', '📦 Material'), ('mano_obra', '👷 Mano de Obra'), ('maquinaria', '🚜 Maquinaria'), ('herramienta', '🛠️ Herramienta'), ('servicio', '🔧 Servicio'), ('gastos_generales', '🏢 Gastos Generales'), ('utilidad', '💰 Utilidad'), ('otros', '📋 Otros')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='itempresupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_constructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_presupuestos', models.BooleanField(default=True)),
                ('email_obras', models.BooleanField(default=True)),
                ('email_sistema', models.BooleanField(default=True)),
                ('email_pagos', models.BooleanField(default=True)),
                ('push_presupuestos', models.BooleanField(default=True)),
                ('push_obras', models.BooleanField(default=True)),
                ('push_sistema', models.BooleanField(default=True)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('silenciar_temporalmente', models.BooleanField(default=False)),
                ('silenciar_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presupuesto_creado', '📋 Presupuesto Creado'), ('presupuesto_aceptado', '✅ Presupuesto Aceptado'), ('presupuesto_rechazado', '❌ Presupuesto Rechazado'), ('obra_iniciada', '🏗️ Obra Iniciada'), ('obra_finalizada', '🎉 Obra Finalizada'), ('material_stock_bajo', '📦 Stock Bajo'), ('pago_realizado', '💰 Pago Realizado'), ('sistema', '🔔 Notificación del Sistema'), ('importante', '⚠️ Importante')], default='sistema', max_length=25)),
                ('titulo', models.CharField(max_length=250)),
                ('mensaje', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.obra')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.presupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='gestion_not_usuario_88a3e4_idx'), models.Index(fields=['fecha_creacion'], name='gestion_not_fecha_c_3ad2be_idx')],
            },
        ),
    ]
