# Generated by Django 5.2.7 on 2025-12-10 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_conversacion_mensaje_mensajeleido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal para el tag', max_length=7)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (ej: fas fa-code)', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag de Repositorio',
                'verbose_name_plural': 'Tags de Repositorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RepositorioGitHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del repositorio', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del proyecto')),
                ('url_repositorio', models.URLField(help_text='URL del repositorio en GitHub')),
                ('url_demo', models.URLField(blank=True, help_text='URL de demo en vivo', null=True)),
                ('url_documentacion', models.URLField(blank=True, help_text='URL de documentación', null=True)),
                ('tipo_proyecto', models.CharField(choices=[('web_app', '🌐 Aplicación Web'), ('mobile_app', '📱 Aplicación Móvil'), ('desktop_app', '💻 Aplicación de Escritorio'), ('api_backend', '⚙️ API/Backend'), ('frontend', '🎨 Frontend'), ('fullstack', '🔄 Full Stack'), ('machine_learning', '🤖 Machine Learning'), ('data_science', '📊 Data Science'), ('game', '🎮 Juego'), ('library', '📚 Librería/Framework'), ('tool', '🛠️ Herramienta'), ('script', '📜 Script/Automatización'), ('website', '🌍 Sitio Web'), ('portfolio', '💼 Portfolio'), ('educational', '🎓 Educativo'), ('experimental', '🧪 Experimental'), ('construction', '🏗️ Construcción/Obras'), ('business', '💼 Empresarial'), ('ecommerce', '🛒 E-commerce'), ('cms', '📝 CMS')], default='web_app', max_length=30)),
                ('tecnologia_principal', models.CharField(choices=[('python', '🐍 Python'), ('django', '🎯 Django'), ('javascript', '💛 JavaScript'), ('react', '⚛️ React'), ('vue', '💚 Vue.js'), ('angular', '🔴 Angular'), ('nodejs', '💚 Node.js'), ('php', '🐘 PHP'), ('laravel', '🔴 Laravel'), ('java', '☕ Java'), ('spring', '🍃 Spring'), ('csharp', '💙 C#'), ('dotnet', '🔵 .NET'), ('flutter', '💙 Flutter'), ('react_native', '📱 React Native'), ('swift', '🍎 Swift'), ('kotlin', '🟠 Kotlin'), ('go', '🔵 Go'), ('rust', '🦀 Rust'), ('typescript', '💙 TypeScript'), ('html_css', '🎨 HTML/CSS'), ('bootstrap', '🟣 Bootstrap'), ('tailwind', '💨 Tailwind CSS'), ('mysql', '🐬 MySQL'), ('postgresql', '🐘 PostgreSQL'), ('mongodb', '🍃 MongoDB'), ('redis', '🔴 Redis'), ('docker', '🐳 Docker'), ('kubernetes', '☸️ Kubernetes'), ('aws', '☁️ AWS'), ('firebase', '🔥 Firebase'), ('other', '🔧 Otro')], default='python', max_length=30)),
                ('tecnologias_adicionales', models.JSONField(blank=True, default=list, help_text='Lista de tecnologías adicionales')),
                ('estado', models.CharField(choices=[('activo', '✅ Activo'), ('en_desarrollo', '🚧 En Desarrollo'), ('completado', '🎉 Completado'), ('mantenimiento', '🔧 En Mantenimiento'), ('archivado', '📦 Archivado'), ('pausado', '⏸️ Pausado'), ('descontinuado', '❌ Descontinuado')], default='activo', max_length=20)),
                ('progreso_porcentaje', models.IntegerField(default=0, help_text='Progreso del proyecto (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('github_id', models.CharField(blank=True, help_text='ID del repositorio en GitHub', max_length=50, null=True)),
                ('estrellas', models.IntegerField(default=0, help_text='Número de estrellas en GitHub')),
                ('forks', models.IntegerField(default=0, help_text='Número de forks')),
                ('watchers', models.IntegerField(default=0, help_text='Número de watchers')),
                ('issues_abiertas', models.IntegerField(default=0, help_text='Issues abiertas')),
                ('lenguaje_principal', models.CharField(blank=True, max_length=50, null=True)),
                ('tamaño_kb', models.IntegerField(default=0, help_text='Tamaño del repositorio en KB')),
                ('fecha_creacion_github', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_commit', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_release', models.DateTimeField(blank=True, null=True)),
                ('es_privado', models.BooleanField(default=False)),
                ('es_fork', models.BooleanField(default=False)),
                ('tiene_wiki', models.BooleanField(default=False)),
                ('tiene_pages', models.BooleanField(default=False)),
                ('licencia', models.CharField(blank=True, max_length=100, null=True)),
                ('es_destacado', models.BooleanField(default=False, help_text='Marcar como proyecto destacado')),
                ('es_comercial', models.BooleanField(default=False, help_text='Proyecto comercial/empresarial')),
                ('es_open_source', models.BooleanField(default=True, help_text='Proyecto de código abierto')),
                ('dificultad', models.IntegerField(choices=[(1, '⭐ Básico'), (2, '⭐⭐ Intermedio'), (3, '⭐⭐⭐ Avanzado'), (4, '⭐⭐⭐⭐ Experto'), (5, '⭐⭐⭐⭐⭐ Maestro')], default=2)),
                ('calidad_codigo', models.IntegerField(choices=[(1, '⭐ Básica'), (2, '⭐⭐ Buena'), (3, '⭐⭐⭐ Muy Buena'), (4, '⭐⭐⭐⭐ Excelente'), (5, '⭐⭐⭐⭐⭐ Excepcional')], default=3)),
                ('imagen_preview', models.ImageField(blank=True, help_text='Imagen de vista previa', null=True, upload_to='repositorios/previews/')),
                ('capturas_pantalla', models.JSONField(blank=True, default=list, help_text='URLs de capturas de pantalla')),
                ('video_demo', models.URLField(blank=True, help_text='URL de video demo', null=True)),
                ('cliente_proyecto', models.CharField(blank=True, help_text='Cliente para quien se desarrolló', max_length=200, null=True)),
                ('costo_desarrollo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de desarrollo en Guaraníes', max_digits=12, null=True)),
                ('tiempo_desarrollo_horas', models.IntegerField(blank=True, help_text='Tiempo de desarrollo en horas', null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('sincronizado_github', models.BooleanField(default=False)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('descargas', models.IntegerField(default=0)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='repositorios_colaborados', to=settings.AUTH_USER_MODEL)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositorios', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='repositorios', to='gestion.tagrepositorio')),
            ],
            options={
                'verbose_name': 'Repositorio GitHub',
                'verbose_name_plural': 'Repositorios GitHub',
                'ordering': ['-es_destacado', '-fecha_ultimo_commit', '-estrellas'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estrellas', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('watchers', models.IntegerField(default=0)),
                ('issues_abiertas', models.IntegerField(default=0)),
                ('commits_dia', models.IntegerField(default=0)),
                ('vistas_dia', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='gestion.repositoriogithub')),
            ],
            options={
                'verbose_name': 'Estadística de Repositorio',
                'verbose_name_plural': 'Estadísticas de Repositorios',
                'ordering': ['-fecha'],
                'unique_together': {('repositorio', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ComentarioRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, '⭐ 1 Estrella'), (2, '⭐⭐ 2 Estrellas'), (3, '⭐⭐⭐ 3 Estrellas'), (4, '⭐⭐⭐⭐ 4 Estrellas'), (5, '⭐⭐⭐⭐⭐ 5 Estrellas')], null=True)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestion.repositoriogithub')),
            ],
            options={
                'verbose_name': 'Comentario de Repositorio',
                'verbose_name_plural': 'Comentarios de Repositorios',
                'ordering': ['-fecha_comentario'],
                'unique_together': {('repositorio', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='repositoriogithub',
            index=models.Index(fields=['tipo_proyecto', 'tecnologia_principal'], name='gestion_rep_tipo_pr_56f874_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoriogithub',
            index=models.Index(fields=['estado', 'es_destacado'], name='gestion_rep_estado_cb6e0c_idx'),
        ),
        migrations.AddIndex(
            model_name='repositoriogithub',
            index=models.Index(fields=['desarrollador', 'activo'], name='gestion_rep_desarro_2848c6_idx'),
        ),
    ]
