# language_manager.py - GESTOR DE IDIOMAS SUPER AVANZADO
import json
from django.utils.translation import gettext as _

class LanguageManager:
    """Gestor de idiomas para el sistema L.u.M.a"""
    
    LANGUAGES = {
        'es': {'name': 'Español Latino', 'flag': '🇪🇸', 'code': 'es'},
        'gn': {'name': 'Guaraní', 'flag': '🇵🇾', 'code': 'gn'},
        'en': {'name': 'English', 'flag': '🇺🇸', 'code': 'en'},
        'pt': {'name': 'Português', 'flag': '🇧🇷', 'code': 'pt'},
        'ja': {'name': '日本語', 'flag': '🇯🇵', 'code': 'ja'},
        'ru': {'name': 'Русский', 'flag': '🇷🇺', 'code': 'ru'},
        'ko': {'name': '한국어', 'flag': '🇰🇷', 'code': 'ko'},
        'fr': {'name': 'Français', 'flag': '🇫🇷', 'code': 'fr'},
        'de': {'name': 'Deutsch', 'flag': '🇩🇪', 'code': 'de'},
        'it': {'name': 'Italiano', 'flag': '🇮🇹', 'code': 'it'},
        'zh': {'name': '中文', 'flag': '🇨🇳', 'code': 'zh'},
        'ar': {'name': 'العربية', 'flag': '🇸🇦', 'code': 'ar'},
        'hi': {'name': 'हिन्दी', 'flag': '🇮🇳', 'code': 'hi'},
        'tr': {'name': 'Türkçe', 'flag': '🇹🇷', 'code': 'tr'},
        'nl': {'name': 'Nederlands', 'flag': '🇳🇱', 'code': 'nl'},
        'sv': {'name': 'Svenska', 'flag': '🇸🇪', 'code': 'sv'},
        'no': {'name': 'Norsk', 'flag': '🇳🇴', 'code': 'no'},
        'da': {'name': 'Dansk', 'flag': '🇩🇰', 'code': 'da'},
        'fi': {'name': 'Suomi', 'flag': '🇫🇮', 'code': 'fi'},
        'pl': {'name': 'Polski', 'flag': '🇵🇱', 'code': 'pl'},
        'cs': {'name': 'Čeština', 'flag': '🇨🇿', 'code': 'cs'},
        'hu': {'name': 'Magyar', 'flag': '🇭🇺', 'code': 'hu'},
        'ro': {'name': 'Română', 'flag': '🇷🇴', 'code': 'ro'},
        'el': {'name': 'Ελληνικά', 'flag': '🇬🇷', 'code': 'el'},
        'he': {'name': 'עברית', 'flag': '🇮🇱', 'code': 'he'},
    }
    
    TRANSLATIONS = {
        # NAVEGACIÓN Y MENÚS
        'dashboard': {
            'es': 'Dashboard',
            'gn': 'Ñemboguata',
            'en': 'Dashboard',
            'pt': 'Painel',
            'ja': 'ダッシュボード',
            'ru': 'Панель управления',
            'ko': '대시보드',
            'fr': 'Tableau de bord',
            'de': 'Dashboard',
            'it': 'Cruscotto',
            'zh': '仪表板',
            'ar': 'لوحة التحكم',
            'hi': 'डैशबोर्ड',
            'tr': 'Kontrol Paneli',
            'nl': 'Dashboard',
            'sv': 'Instrumentpanel',
            'no': 'Dashbord',
            'da': 'Dashboard',
            'fi': 'Kojelauta',
            'pl': 'Panel',
            'cs': 'Nástěnka',
            'hu': 'Irányítópult',
            'ro': 'Tablou de bord',
            'el': 'Πίνακας ελέγχου',
            'he': 'לוח בקרה'
        },
        'obras': {
            'es': 'Obras',
            'gn': 'Mba\'apo',
            'en': 'Projects',
            'pt': 'Obras',
            'ja': 'プロジェクト',
            'ru': 'Проекты',
            'ko': '프로젝트',
            'fr': 'Projets',
            'de': 'Projekte',
            'it': 'Progetti',
            'zh': '项目',
            'ar': 'المشاريع',
            'hi': 'परियोजनाएं',
            'tr': 'Projeler',
            'nl': 'Projecten',
            'sv': 'Projekt',
            'no': 'Prosjekter',
            'da': 'Projekter',
            'fi': 'Projektit',
            'pl': 'Projekty',
            'cs': 'Projekty',
            'hu': 'Projektek',
            'ro': 'Proiecte',
            'el': 'Έργα',
            'he': 'פרויקטים'
        },
        'presupuestos': {
            'es': 'Presupuestos',
            'gn': 'Viru repy',
            'en': 'Budgets',
            'pt': 'Orçamentos',
            'ja': '予算',
            'ru': 'Бюджеты',
            'ko': '예산',
            'fr': 'Budgets',
            'de': 'Budgets',
            'it': 'Budget',
            'zh': '预算',
            'ar': 'الميزانيات',
            'hi': 'बजट',
            'tr': 'Bütçeler',
            'nl': 'Budgetten',
            'sv': 'Budgetar',
            'no': 'Budsjetter',
            'da': 'Budgetter',
            'fi': 'Budjetit',
            'pl': 'Budżety',
            'cs': 'Rozpočty',
            'hu': 'Költségvetések',
            'ro': 'Bugete',
            'el': 'Προϋπολογισμοί',
            'he': 'תקציבים'
        },
        'materiales': {
            'es': 'Materiales',
            'gn': 'Mba\'e',
            'en': 'Materials',
            'pt': 'Materiais',
            'ja': '材料',
            'ru': 'Материалы',
            'ko': '재료',
            'fr': 'Matériaux',
            'de': 'Materialien',
            'it': 'Materiali',
            'zh': '材料',
            'ar': 'المواد',
            'hi': 'सामग्री',
            'tr': 'Malzemeler',
            'nl': 'Materialen',
            'sv': 'Material',
            'no': 'Materialer',
            'da': 'Materialer',
            'fi': 'Materiaalit',
            'pl': 'Materiały',
            'cs': 'Materiály',
            'hu': 'Anyagok',
            'ro': 'Materiale',
            'el': 'Υλικά',
            'he': 'חומרים'
        },
        'contratistas': {
            'es': 'Contratistas',
            'gn': 'Mba\'apoha',
            'en': 'Contractors',
            'pt': 'Empreiteiros',
            'ja': '請負業者',
            'ru': 'Подрядчики',
            'ko': '계약자',
            'fr': 'Entrepreneurs',
            'de': 'Auftragnehmer',
            'it': 'Appaltatori',
            'zh': '承包商',
            'ar': 'المقاولون',
            'hi': 'ठेकेदार',
            'tr': 'Müteahhitler',
            'nl': 'Aannemers',
            'sv': 'Entreprenörer',
            'no': 'Entreprenører',
            'da': 'Entreprenører',
            'fi': 'Urakoitsijat',
            'pl': 'Wykonawcy',
            'cs': 'Dodavatelé',
            'hu': 'Vállalkozók',
            'ro': 'Contractori',
            'el': 'Εργολάβοι',
            'he': 'קבלנים'
        },
        'empleados': {
            'es': 'Empleados',
            'gn': 'Mba\'apohára',
            'en': 'Employees',
            'pt': 'Funcionários',
            'ja': '従業員',
            'ru': 'Сотрудники',
            'ko': '직원',
            'fr': 'Employés',
            'de': 'Mitarbeiter',
            'it': 'Dipendenti',
            'zh': '员工',
            'ar': 'الموظفون',
            'hi': 'कर्मचारी',
            'tr': 'Çalışanlar',
            'nl': 'Werknemers',
            'sv': 'Anställda',
            'no': 'Ansatte',
            'da': 'Medarbejdere',
            'fi': 'Työntekijät',
            'pl': 'Pracownicy',
            'cs': 'Zaměstnanci',
            'hu': 'Alkalmazottak',
            'ro': 'Angajați',
            'el': 'Υπάλληλοι',
            'he': 'עובדים'
        },
        'proveedores': {
            'es': 'Proveedores',
            'gn': 'Me\'ẽha',
            'en': 'Suppliers',
            'pt': 'Fornecedores',
            'ja': 'サプライヤー',
            'ru': 'Поставщики',
            'ko': '공급업체',
            'fr': 'Fournisseurs',
            'de': 'Lieferanten',
            'it': 'Fornitori',
            'zh': '供应商',
            'ar': 'الموردون',
            'hi': 'आपूर्तिकर्ता',
            'tr': 'Tedarikçiler',
            'nl': 'Leveranciers',
            'sv': 'Leverantörer',
            'no': 'Leverandører',
            'da': 'Leverandører',
            'fi': 'Toimittajat',
            'pl': 'Dostawcy',
            'cs': 'Dodavatelé',
            'hu': 'Beszállítók',
            'ro': 'Furnizori',
            'el': 'Προμηθευτές',
            'he': 'ספקים'
        },
        # ACCIONES COMUNES
        'crear': {
            'es': 'Crear',
            'gn': 'Japo',
            'en': 'Create',
            'pt': 'Criar',
            'ja': '作成',
            'ru': 'Создать',
            'ko': '생성',
            'fr': 'Créer',
            'de': 'Erstellen',
            'it': 'Creare',
            'zh': '创建',
            'ar': 'إنشاء',
            'hi': 'बनाएं',
            'tr': 'Oluştur',
            'nl': 'Aanmaken',
            'sv': 'Skapa',
            'no': 'Opprett',
            'da': 'Opret',
            'fi': 'Luo',
            'pl': 'Utwórz',
            'cs': 'Vytvořit',
            'hu': 'Létrehozás',
            'ro': 'Creează',
            'el': 'Δημιουργία',
            'he': 'צור'
        },
        'editar': {
            'es': 'Editar',
            'gn': 'Moambue',
            'en': 'Edit',
            'pt': 'Editar',
            'ja': '編集',
            'ru': 'Редактировать',
            'ko': '편집',
            'fr': 'Modifier',
            'de': 'Bearbeiten',
            'it': 'Modifica',
            'zh': '编辑',
            'ar': 'تحرير',
            'hi': 'संपादित करें',
            'tr': 'Düzenle',
            'nl': 'Bewerken',
            'sv': 'Redigera',
            'no': 'Rediger',
            'da': 'Rediger',
            'fi': 'Muokkaa',
            'pl': 'Edytuj',
            'cs': 'Upravit',
            'hu': 'Szerkesztés',
            'ro': 'Editează',
            'el': 'Επεξεργασία',
            'he': 'ערוך'
        },
        'eliminar': {
            'es': 'Eliminar',
            'gn': 'Mbogue',
            'en': 'Delete',
            'pt': 'Excluir',
            'ja': '削除',
            'ru': 'Удалить',
            'ko': '삭제',
            'fr': 'Supprimer',
            'de': 'Löschen',
            'it': 'Elimina',
            'zh': '删除',
            'ar': 'حذف',
            'hi': 'हटाएं',
            'tr': 'Sil',
            'nl': 'Verwijderen',
            'sv': 'Ta bort',
            'no': 'Slett',
            'da': 'Slet',
            'fi': 'Poista',
            'pl': 'Usuń',
            'cs': 'Smazat',
            'hu': 'Törlés',
            'ro': 'Șterge',
            'el': 'Διαγραφή',
            'he': 'מחק'
        },
        'guardar': {
            'es': 'Guardar',
            'gn': 'Ñongatu',
            'en': 'Save',
            'pt': 'Salvar',
            'ja': '保存',
            'ru': 'Сохранить',
            'ko': '저장',
            'fr': 'Enregistrer',
            'de': 'Speichern',
            'it': 'Salva',
            'zh': '保存',
            'ar': 'حفظ',
            'hi': 'सहेजें',
            'tr': 'Kaydet',
            'nl': 'Opslaan',
            'sv': 'Spara',
            'no': 'Lagre',
            'da': 'Gem',
            'fi': 'Tallenna',
            'pl': 'Zapisz',
            'cs': 'Uložit',
            'hu': 'Mentés',
            'ro': 'Salvează',
            'el': 'Αποθήκευση',
            'he': 'שמור'
        },
        'cancelar': {
            'es': 'Cancelar',
            'gn': 'Jokua',
            'en': 'Cancel',
            'pt': 'Cancelar',
            'ja': 'キャンセル',
            'ru': 'Отменить',
            'ko': '취소',
            'fr': 'Annuler',
            'de': 'Abbrechen',
            'it': 'Annulla',
            'zh': '取消',
            'ar': 'إلغاء',
            'hi': 'रद्द करें',
            'tr': 'İptal',
            'nl': 'Annuleren',
            'sv': 'Avbryt',
            'no': 'Avbryt',
            'da': 'Annuller',
            'fi': 'Peruuta',
            'pl': 'Anuluj',
            'cs': 'Zrušit',
            'hu': 'Mégse',
            'ro': 'Anulează',
            'el': 'Ακύρωση',
            'he': 'בטל'
        },
        # ESTADOS
        'activo': {
            'es': 'Activo',
            'gn': 'Oiko',
            'en': 'Active',
            'pt': 'Ativo',
            'ja': 'アクティブ',
            'ru': 'Активный',
            'ko': '활성',
            'fr': 'Actif',
            'de': 'Aktiv',
            'it': 'Attivo',
            'zh': '活跃',
            'ar': 'نشط',
            'hi': 'सक्रिय',
            'tr': 'Aktif',
            'nl': 'Actief',
            'sv': 'Aktiv',
            'no': 'Aktiv',
            'da': 'Aktiv',
            'fi': 'Aktiivinen',
            'pl': 'Aktywny',
            'cs': 'Aktivní',
            'hu': 'Aktív',
            'ro': 'Activ',
            'el': 'Ενεργός',
            'he': 'פעיל'
        },
        'disponible': {
            'es': 'Disponible',
            'gn': 'Ojepuru',
            'en': 'Available',
            'pt': 'Disponível',
            'ja': '利用可能',
            'ru': 'Доступно',
            'ko': '사용 가능',
            'fr': 'Disponible',
            'de': 'Verfügbar',
            'it': 'Disponibile',
            'zh': '可用',
            'ar': 'متاح',
            'hi': 'उपलब्ध',
            'tr': 'Mevcut',
            'nl': 'Beschikbaar',
            'sv': 'Tillgänglig',
            'no': 'Tilgjengelig',
            'da': 'Tilgængelig',
            'fi': 'Saatavilla',
            'pl': 'Dostępny',
            'cs': 'Dostupný',
            'hu': 'Elérhető',
            'ro': 'Disponibil',
            'el': 'Διαθέσιμος',
            'he': 'זמין'
        },
        # TÍTULOS Y MENSAJES
        'bienvenido': {
            'es': 'Bienvenido',
            'gn': 'Tereg̃uahẽporãite',
            'en': 'Welcome',
            'pt': 'Bem-vindo',
            'ja': 'ようこそ',
            'ru': 'Добро пожаловать',
            'ko': '환영합니다',
            'fr': 'Bienvenue',
            'de': 'Willkommen',
            'it': 'Benvenuto',
            'zh': '欢迎',
            'ar': 'مرحبا',
            'hi': 'स्वागत है',
            'tr': 'Hoş geldiniz',
            'nl': 'Welkom',
            'sv': 'Välkommen',
            'no': 'Velkommen',
            'da': 'Velkommen',
            'fi': 'Tervetuloa',
            'pl': 'Witamy',
            'cs': 'Vítejte',
            'hu': 'Üdvözöljük',
            'ro': 'Bun venit',
            'el': 'Καλώς ήρθατε',
            'he': 'ברוך הבא'
        },
        'sistema_gestion': {
            'es': 'Sistema de Gestión de Presupuestos para Obras Civiles',
            'gn': 'Sistema de Ñangareko Viru repy Mba\'apo Civil-pe g̃uarã',
            'en': 'Civil Works Budget Management System',
            'pt': 'Sistema de Gestão de Orçamentos para Obras Civis',
            'ja': '土木工事予算管理システム',
            'ru': 'Система управления бюджетами гражданских работ',
            'ko': '토목 공사 예산 관리 시스템',
            'fr': 'Système de Gestion des Budgets pour Travaux Civils',
            'de': 'Budgetverwaltungssystem für Tiefbauarbeiten',
            'it': 'Sistema di Gestione Budget per Lavori Civili',
            'zh': '土木工程预算管理系统',
            'ar': 'نظام إدارة ميزانيات الأعمال المدنية',
            'hi': 'सिविल वर्क्स बजट प्रबंधन प्रणाली',
            'tr': 'İnşaat İşleri Bütçe Yönetim Sistemi',
            'nl': 'Budgetbeheersysteem voor Civiele Werken',
            'sv': 'Budgethanteringssystem för Anläggningsarbeten',
            'no': 'Budsjettadministrasjonssystem for Anleggsarbeid',
            'da': 'Budgetstyringssystem til Anlægsarbejde',
            'fi': 'Rakennustöiden Budjettinhallintajärjestelmä',
            'pl': 'System Zarządzania Budżetami Robót Budowlanych',
            'cs': 'Systém Řízení Rozpočtů Stavebních Prací',
            'hu': 'Építési Munkák Költségvetés Kezelő Rendszer',
            'ro': 'Sistem de Gestionare Bugete pentru Lucrări Civile',
            'el': 'Σύστημα Διαχείρισης Προϋπολογισμών Πολιτικών Έργων',
            'he': 'מערכת ניהול תקציבים לעבודות אזרחיות'
        }
    }
    
    @classmethod
    def get_translation(cls, key, language='es'):
        """Obtiene la traducción de una clave en el idioma especificado"""
        if key in cls.TRANSLATIONS and language in cls.TRANSLATIONS[key]:
            return cls.TRANSLATIONS[key][language]
        return cls.TRANSLATIONS.get(key, {}).get('es', key)
    
    @classmethod
    def get_language_info(cls, code):
        """Obtiene información del idioma por código"""
        return cls.LANGUAGES.get(code, cls.LANGUAGES['es'])
    
    @classmethod
    def get_all_languages(cls):
        """Obtiene todos los idiomas disponibles"""
        return cls.LANGUAGES