"""
Django settings for mi_tienda project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gsfy__8cf1nyg)9em$x1k)=ce$5k2i7$$xo5)#&-*_0-h&^*9='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'tu-dominio.com', 'testserver']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware personalizado habilitado
    'gestion.middleware_mejorado.AuditoriaMiddlewareMejorado',
]

ROOT_URLCONF = 'mi_tienda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_tienda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'  # ⭐ CAMBIADO a español
TIME_ZONE = 'America/Asuncion'  # ⭐ CAMBIADO a tu zona horaria
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración para servir archivos media en desarrollo
if DEBUG:
    import os
    from django.conf.urls.static import static
    # Esta configuración se aplicará automáticamente en urls.py

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================
# ⭐ CONFIGURACIÓN DE AUTENTICACIÓN PERSONALIZADA
# =============================================
AUTH_USER_MODEL = 'gestion.UsuarioPersonalizado'

# URLs de autenticación
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'


# =============================================
# ⭐ CONFIGURACIÓN DE ARCHIVOS MULTIMEDIA
# =============================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# =============================================
# ⭐ CONFIGURACIÓN DE EMAILS
# =============================================
# Para desarrollo (muestra emails en consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Mi Tienda Premium <noreply@mitienda.com>'

# Para producción con Gmail (descomenta cuando vayas a producción)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'luma@gmail.com'
# EMAIL_HOST_PASSWORD = '12345678py'  # ⚠️ USA CONTRASEÑA DE APLICACIÓN, NO TU CONTRASEÑA NORMAL
# DEFAULT_FROM_EMAIL = 'Mi Tienda Premium <luma@gmail.com>'


# =============================================
# ⭐ CONFIGURACIÓN DE PERMISOS Y ROLES
# =============================================
PERMISSIONS = {
    'admin': [
        'puede_ver_dashboard',
        'puede_gestionar_productos', 
        'puede_ver_reportes',
        'puede_gestionar_usuarios',
        'puede_crear_producto',
        'puede_editar_producto',
        'puede_eliminar_producto',
    ],
    'vendedor': [
        'puede_ver_dashboard',
        'puede_gestionar_productos',
        'puede_ver_reportes',
        'puede_crear_producto',
        'puede_editar_producto',
    ],
    'cliente': [
        'puede_ver_dashboard',
    ]
}


# =============================================
# ⭐ CONFIGURACIÓN DE SEGURIDAD
# =============================================
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Configuración de sesiones
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Para producción (descomenta cuando vayas a HTTPS)
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True


# =============================================
# ⭐ CONFIGURACIÓN DE NOTIFICACIONES
# =============================================
ADMINS = [
    ('Admin', 'admin@mitienda.com'),
]
MANAGERS = ADMINS

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'auditoria': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'auditoria.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'auditoria': {
            'handlers': ['auditoria', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'gestion': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
# Configuración de formato para Paraguay
USE_L10N = True
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3

# Formato de moneda personalizado
from django.utils.formats import get_format

FORMAT_MODULE_PATH = [
    'mi_tienda.formats',
]


# Agregar al final de settings.py
import os

# Configuración para reportes PDF
WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'  # Linux
WKHTMLTOPDF_CMD = 'C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe'  # Windows

# Configuración de reportlab
PDF_STYLES = {
    'primary_color': '#1a365d',
    'secondary_color': '#2d74da', 
    'accent_color': '#00b894',
    'danger_color': '#e17055',
    'font_name': 'Helvetica',
}

# Directorio para reportes temporales
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
REPORTS_DIR = os.path.join(MEDIA_ROOT, 'reports')
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(REPORTS_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)

# =============================================
# ⭐ CONFIGURACIÓN DE CACHE
# =============================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Configuración WebSockets (deshabilitada temporalmente)
# ASGI_APPLICATION = "mi_tienda.asgi.application"
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels.layers.InMemoryChannelLayer'
#     }
# }

# =============================================
# ⭐ CONFIGURACIÓN PWA (DESHABILITADA)
# =============================================
# PWA configuración deshabilitada hasta instalar django-pwa
# Para habilitar: pip install django-pwa y agregar 'pwa' a INSTALLED_APPS

# =============================================
# ⭐ CONFIGURACIÓN DE MENSAJES
# =============================================
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# =============================================
# ⭐ CONFIGURACIÓN DE CONTEXTO GLOBAL
# =============================================
# Context processors configurados en TEMPLATES

# =============================================
# ⭐ CONFIGURACIÓN DE DESARROLLO/PRODUCCIÓN
# =============================================
if DEBUG:
    # Configuraciones solo para desarrollo
    INTERNAL_IPS = ['127.0.0.1', 'localhost']
    
    # Mostrar toolbar de debug si está instalado
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
        MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    except ImportError:
        pass
else:
    # Configuraciones para producción
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Logging más estricto en producción
    LOGGING['loggers']['django']['level'] = 'WARNING'
    LOGGING['loggers']['gestion']['level'] = 'INFO'